from .habitat_types.terrestrial import ITerrestrial
from .habitat_types.aquatic import IAquatic
from .movement_types.flying import IFlying
from .movement_types.walking import IWalking
from .movement_types.swimming import ISwimming
from .indentifiable import Identifiable
from .contains_animals import IContainsAnimals
from .contains_plants import IContainsPlants
from .water_types.stagnant import IStagnant
from .water_types.salty import ISalty
from .water_types.brackish import IBrackish
